# Generated by Django 5.1.7 on 2025-04-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_vacancy_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Отчет'),
        ),
    ]
